version: "3.10"

services:
  tiktok_scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiktok_scrapper
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    network_mode: "host" # Используем сеть хоста
